rov_blog_article_search:
    pattern:  /search
    defaults: { _controller: ROVBlogBundle:Default:articleSearch }
    methods:  [POST]

rov_blog_article_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Default:articleCategory, page: 1 }
    requirements:
        page:  \d+

rov_blog_article_tag:
    pattern:  /tag/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Default:articleTag, page: 1 }
    requirements:
        page:  \d+

rov_blog_new_article:
    pattern:  /admin/new
    defaults: { _controller: ROVBlogBundle:Default:newArticle }

rov_blog_edit_article:
    pattern:  /admin/edit/{article_id}
    defaults: { _controller: ROVBlogBundle:Default:editArticle }

rov_blog_delete_article:
    pattern:  /admin/delete/{article_id}
    defaults: { _controller: ROVBlogBundle:Default:deleteArticle }

rov_blog_manage_articles:
    pattern:  /admin/manage
    defaults: { _controller: ROVBlogBundle:Default:manageArticles }

rov_blog_article:
    pattern:  /{slug}
    defaults: { _controller: ROVBlogBundle:Default:article }

rov_blog_homepage:
    pattern:  /{page}
    defaults: { _controller: ROVBlogBundle:Default:blogHome, page: 1 }
    requirements:
        page:  \d+

