rov_blog_homepage:
    pattern:  /{page}
    defaults: { _controller: ROVBlogBundle:Default:index, page: 1 }
    requirements:
        page:  \d+

rov_blog_article:
    pattern:  /{slug}
    defaults: { _controller: ROVBlogBundle:Default:article }

rov_blog_search:
    pattern:  /search
    defaults: { _controller: ROVBlogBundle:Default:search }
    methods:  [POST]