rov_blog_article_search:
    pattern:  /search
    defaults: { _controller: ROVBlogBundle:Default:articleSearch }

rov_blog_article_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Default:articleCategory, page: 1 }
    requirements:
        page:  \d+

rov_blog_article_tag:
    pattern:  /tag/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Default:articleTag, page: 1 }
    requirements:
        page:  \d+

rov_blog_article_date:
    pattern:  /date/{year}/{month}/{page}
    defaults: { _controller: ROVBlogBundle:Default:articleDate, month: 0, page: 1 }
    requirements:
        page:  \d+

rov_blog_new_article:
    pattern:  /admin/new/article
    defaults: { _controller: ROVBlogBundle:Default:newArticle }

rov_blog_new_wine:
    pattern:  /admin/new/wine
    defaults: { _controller: ROVBlogBundle:Wine:newWine }

rov_blog_edit_article:
    pattern:  /admin/edit/article/{article_id}
    defaults: { _controller: ROVBlogBundle:Default:editArticle }

rov_blog_edit_wine:
    pattern:  /admin/edit/wine/{wine_id}
    defaults: { _controller: ROVBlogBundle:Wine:editWine }

rov_blog_preview_article:
    pattern:  /admin/preview/article/{article_id}
    defaults: { _controller: ROVBlogBundle:Default:previewArticle }

rov_blog_preview_wine:
    pattern:  /admin/preview/wine/{wine_id}
    defaults: { _controller: ROVBlogBundle:Wine:previewWine }

rov_blog_delete_article:
    pattern:  /admin/delete/article/{article_id}
    defaults: { _controller: ROVBlogBundle:Default:deleteArticle }

rov_blog_manage_articles:
    pattern:  /admin/manage/articles
    defaults: { _controller: ROVBlogBundle:Default:manageArticles }

rov_blog_manage_category:
    pattern:  /admin/manage/category/{slug}
    defaults: { _controller: ROVBlogBundle:Default:manageCategory }

rov_blog_manage_tag:
    pattern:  /admin/manage/tag/{slug}
    defaults: { _controller: ROVBlogBundle:Default:manageTag }

rov_blog_manage_wines:
    pattern:  /admin/manage/wines
    defaults: { _controller: ROVBlogBundle:Wine:manageWines }

rov_blog_manage_region:
    pattern:  /admin/manage/region/{slug}
    defaults: { _controller: ROVBlogBundle:Wine:manageRegion }

rov_blog_manage_winery:
    pattern:  /admin/manage/winery/{slug}
    defaults: { _controller: ROVBlogBundle:Wine:manageWinery }

rov_blog_accept_comment:
    pattern:  /admin/comment/accept/{article_id}/{comment_id}
    defaults: { _controller: ROVBlogBundle:Default:acceptComment }

rov_blog_delete_comment:
    pattern:  /admin/comment/delete/{article_id}/{comment_id}
    defaults: { _controller: ROVBlogBundle:Default:deleteComment }

rov_blog_article:
    pattern:  /article/{slug}
    defaults: { _controller: ROVBlogBundle:Default:article }

rov_blog_wine_homepage:
    pattern:  /wines/{page}
    defaults: { _controller: ROVBlogBundle:Wine:wineReviews, page: 1 }
    requirements:
        page:  \d+

rov_blog_wine_review:
    pattern:  /wine/review/{slug}
    defaults: { _controller: ROVBlogBundle:Wine:wine }

rov_blog_wine_search:
    pattern:  /wines/search
    defaults: { _controller: ROVBlogBundle:Wine:wineReviewSearch }

rov_blog_wine_region:
    pattern:  /wines/region/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Wine:wineReviewsRegion, page: 1 }
    requirements:
        page:  \d+

rov_blog_wine_winery:
    pattern:  /wines/winery/{slug}/{page}
    defaults: { _controller: ROVBlogBundle:Wine:wineReviewsWinery, page: 1 }
    requirements:
        page:  \d+

rov_blog_wine_date:
    pattern:  /wines/date/{year}/{month}/{page}
    defaults: { _controller: ROVBlogBundle:Wine:wineReviewsDate, month: 0, page: 1 }
    requirements:
        page:  \d+

rov_blog_delete_wine:
    pattern:  /admin/delete/wine/{wine_id}
    defaults: { _controller: ROVBlogBundle:Wine:deleteWineReview }

rov_blog_homepage:
    pattern:  /{page}
    defaults: { _controller: ROVBlogBundle:Default:blogHome, page: 1 }
    requirements:
        page:  \d+

