rov_start_homepage:
    pattern:  /home
    defaults: { _controller: ROVStartBundle:Default:home }

rov_start_contact:
    pattern:  /contact
    defaults: { _controller: ROVStartBundle:Default:contact }

rov_start_static:
    pattern:  /site/{page}
    defaults: { _controller: ROVStartBundle:Site:static }