security:
    encoders:
        ROV\UsersBundle\Entity\User:
            algorithm: sha512
            iterations: 10
            encode_as_base64: true
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    santos: { password: b8a4634ede88c061f6e85125870897fd29b3e46f, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    raquel: { password: 370a7287c1504d83be04f11b1565818f31271c04, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: ROV\UsersBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        frontend:
            pattern:        ^/*
            anonymous:      ~
            form_login:  
                login_path: rov_users_login
                check_path: rov_users_login_check
            logout:
                path:       rov_users_logout
                target:     home
                invalidate_session: false
            remember_me:
                key:        rovwebloguser2014
                lifetime:   86400   # 86.400 = 60 * 60 * 24 = 1 day
                path:       /
                domain:     ~       # Defaults to the current domain from $_SERVER
        admin:
            pattern:        ^/admin*
            provider:       in_memory
            form_login:  
                login_path: user_login
                check_path: user_login_check
            logout:
                path:       user_logout
                target:     home
                invalidate_session: false
            remember_me:
                key:        rovweblogadmin2014
                lifetime:   86400   # 86.400 = 60 * 60 * 24 = 1 day
                path:       /
                domain:     ~       # Defaults to the current domain from $_SERVER

    access_control:
        - { path: '^/[a-z]{2}/user/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/admin', roles: ROLE_ADMIN }
