security:
    encoders:
        ROV\UsersBundle\Entity\User:
            algorithm: sha512
            iterations: 10
            encode_as_base64: true

    role_hierarchy:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       ROLE_MODERATOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: ROV\UsersBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        frontend:
            pattern:        ^/*
            anonymous:      ~
            provider:       user_db
            form_login:  
                login_path: rov_users_login
                check_path: rov_users_login_check
            logout:
                path:       rov_users_logout
                target:     home
                invalidate_session: false
            remember_me:
                key:        rovwebloguser2014
                lifetime:   86400   # 86.400 = 60 * 60 * 24 = 1 day
                path:       /
                domain:     ~       # Defaults to the current domain from $_SERVER
        admin:
            pattern:        ^/admin*
            provider:       user_db
            form_login:  
                login_path: rov_users_login
                check_path: rov_users_login_check
            logout:
                path:       rov_users_logout
                target:     home
                invalidate_session: false
            remember_me:
                key:        rovweblogadmin2014
                lifetime:   86400   # 86.400 = 60 * 60 * 24 = 1 day
                path:       /
                domain:     ~       # Defaults to the current domain from $_SERVER

    access_control:
        - { path: '^/[a-z]{2}/user/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/user/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/admin', roles: ROLE_ADMIN }
