rov_users_homepage:
    pattern:  /
    defaults: { _controller: ROVUsersBundle:Default:profile }

rov_users_login:
    pattern:  /login
    defaults: { _controller: ROVUsersBundle:Default:login }

rov_users_login_check:
    pattern:  /login_check

rov_users_register:
    pattern:  /register
    defaults: { _controller:ROVUsersBundle:Default:register }