parameters:
#    rov_users.example.class: ROV\UsersBundle\Example

services:
    login_listener:
        class: ROV\UsersBundle\Listener\LoginListener
        arguments: ["@security.authorization_checker", "@router"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
